name: chat
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.5
  firebase_dynamic_links: ^0.5.1
  flutter_secure_storage: ^3.3.3
  shared_preferences: ^0.5.7+3
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  equatable: ^1.2.0
  flutter_bloc: ^4.0.0
  country_code_picker: ^1.3.15
  pin_view: ^1.0.1
  connectivity: ^0.4.8+6

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
